In [1]:
#import
import torch

In [16]:
#random tensor
random_tensor_1 = torch.rand(size=(7,7))
random_tensor_1.shape, random_tensor_1

(torch.Size([7, 7]),
 tensor([[0.7097, 0.8759, 0.6007, 0.3747, 0.2941, 0.9243, 0.1348],
         [0.1218, 0.4991, 0.0234, 0.4279, 0.2731, 0.6421, 0.9205],
         [0.2572, 0.7626, 0.3385, 0.7661, 0.3727, 0.4284, 0.7015],
         [0.9441, 0.6767, 0.3881, 0.4034, 0.5061, 0.5801, 0.5940],
         [0.6605, 0.5858, 0.1612, 0.8063, 0.9163, 0.0812, 0.0717],
         [0.4042, 0.5664, 0.7767, 0.2409, 0.3916, 0.4463, 0.7084],
         [0.0604, 0.5134, 0.3058, 0.5896, 0.1246, 0.8533, 0.6117]]))

In [18]:
#random matric multiplication on tensor with another random with shape 1,7, transopose
random_tensor_2 = torch.rand(size=(1,7))
random_tensor_2.T

random_tensor_1.matmul(random_tensor_2.T)

tensor([[2.6023],
        [1.4833],
        [1.9278],
        [2.5539],
        [2.0427],
        [2.1324],
        [1.6479]])

In [21]:
#random seed
torch.manual_seed(0)

random_tensor_1 = torch.rand(size=(7,7))
random_tensor_2 = torch.rand(size=(1,7))

random_tensor_1.matmul(random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [23]:
#random GPU seed
torch.cuda.manual_seed(1234)

In [105]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [112]:
#matmul with transpose for shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [117]:
#Find min and max
tensor_C.max(), tensor_C.min()

(tensor(0.5617), tensor(0.3647))

In [119]:
#Find index
tensor_C.argmax(), tensor_C.argmin()

(tensor(3), tensor(0))

In [144]:
torch.manual_seed(0)

tensor = torch.rand(size=(1,1,1,10))

#remove single dimentions
tensor = tensor.squeeze()

tensor, tensor.shape

(tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323]),
 torch.Size([10]))